<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.0" />
    <PackageReference Include="AvaloniaMath" Version="2.1.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MathKeyboardEngine" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="Resources\Styles.Light.axaml" />
    <AvaloniaResource Include="Resources\Styles.Light.axaml" />
    <AvaloniaXaml Remove="Resources\StringResources.en.axaml" />
    <AvaloniaResource Include="Resources\StringResources.en.axaml" />
    <AvaloniaXaml Remove="Resources\StringResources.bg.axaml" />
    <AvaloniaResource Include="Resources\StringResources.bg.axaml" />
  </ItemGroup>

</Project>
